### ISSUE TITLE
Triggered Alarms

### ISSUE THREAD

**Issue by tubby1981** [atc0005/check-vmware#171]
What you have made works really well. 

Is it also possible to check the "Issues and Alarms" via a plugin? It wouldn't be nice to have to install the perl SDK for that

**Comment by atc0005** [comment]
> What you have made works really well.

Thank you, I appreciate the kind words!

> Is it also possible to check the "Issues and Alarms" via a plugin?

I'm not sure, but I'd be willing to look into it.

> It wouldn't be nice to have to install the perl SDK for that

I completely understand. I was hesitant to install PowerShell & PowerCLI on our Nagios instance for similar reasons in the past. We ended up doing it anyway as the options were more limited for us then.

Do you happen to have any examples where checking the "Issues and Alarms" is accomplished via the perl SDK?

**Comment by tubby1981** [comment]
For example, we use the following plugin for that: 
https://github.com/usolved/check_usolved_vsphere_alarms

and this one to check if consolidation is needed: 
https://github.com/aleex42/VMware-Automation/blob/master/check_vmware_disk_consolidation.pl

**Comment by atc0005** [comment]
Thanks for the examples. 

I may have some time to look at this in the next week. If/when I get something together I'll ping you to take a look. The biggest decider will be whether the govmomi library I'm using has native support, or if it will require something more low-level (which I don't have that much experience with).

**Comment by atc0005** [comment]
I looked at the `check_vmware_disk_consolidation.pl` plugin and I believe I understand what it is doing. I am optimistic that I can use govmomi for this. I will have a go and let you know when there is something to test.

I looked over the vSphere API docs for the other and that may take longer to get my head around. Having a plugin to monitor for alarms (particularly unacknowledged ones) seems like a good fit, so it should be worth it in the end.

**Comment by tubby1981** [comment]
Okay sounds good. Let me know if I can test something.

**Comment by atc0005** [comment]
> @tubby1981: Okay sounds good. Let me know if I can test something.

I've added a new disk consolidation plugin (GH-172). I can't say with absolutely confidence that it works as intended as none of our VMs are reporting the need for disk consolidation, but it *should* work, for whatever that is worth. Feedback is welcome.

I'm going to go ahead and cut a release which includes this new plugin. If you encounter issues with the plugin, please file a new issue and share a sanitized version of the error messages so I can take a closer look.

I'll keep this issue open and dedicated to tracking future efforts towards a vSphere Alarms plugin.

**Comment by tubby1981** [comment]
I'm going to test it. Which VMWare versions are supported? We have no issues on our VMWare 7.X platform yet. But we also have older environments where this problem sometimes occurs

**Comment by atc0005** [comment]
> @tubby1981: Which VMWare versions are supported?

*Should* be the same versions supported by the vmware/govmomi library:

> This library is built for and tested against ESXi and vCenter 6.5, 6.7 and 7.0.
> 
> It may work with versions 5.1, 5.5 and 6.0, but neither are officially supported.

If you find out differently please do file an issue.

Plugins from this project are used in a production 6.7 environment. I'm able to test there, but do not have standalone hosts or older/newer environments to test against.

refs https://github.com/vmware/govmomi#compatibility

**Comment by tubby1981** [comment]
Any luck with writing a plugin for this :-) ?

**Comment by atc0005** [comment]
I have done some initial research, but nothing to show yet. I will ping you just as soon as I have something to show/test. Not sure yet when that will be.

**Comment by atc0005** [comment]
I haven't forgotten about this, just haven't had a lot of off/non-work hours to invest in this or other projects lately. I've made a little progress, just not enough to be useful or show yet.

**Comment by atc0005** [comment]
@tubby1981 

I've got a prototype build working that hopefully provides some useful functionality. If all goes well I hope to cut a new release today, but I still have documentation work and contrib files to craft.

There are additional features that won't make it to the next release, but may in the future. I've noted some of those features on GH-220 and may grow the list based off of real-world usage in the next few weeks.

My access to vSphere environments to test against is limited, so there are likely a number of scenarios that I'm not accounting for.

If you spot missing (or broken) functionality in the upcoming release, please report the details on a new issue and I'll take a look when I can (limited time these days).

**Comment by atc0005** [comment]
> @tubby1981
> 
> I've got a prototype build working that hopefully provides some useful functionality. If all goes well I hope to cut a new release today, but I still have documentation work and contrib files to craft.
> 
> There are additional features that won't make it to the next release, but may in the future. I've noted some of those features on [GH-220](https://github.com/atc0005/check-vmware/issues/220) and may grow the list based off of real-world usage in the next few weeks.
> 
> My access to vSphere environments to test against is limited, so there are likely a number of scenarios that I'm not accounting for.
> 
> If you spot missing (or broken) functionality in the upcoming release, please report the details on a new issue and I'll take a look when I can (limited time these days).

New release: https://github.com/atc0005/check-vmware/releases/tag/v0.16.0

I hope to deploy the new plugin locally tomorrow to get some real world usage in. Please let me know how the new plugin works for you.

**Comment by tubby1981** [comment]
@atc0005 

I'm currently testing the plugin. There is overlap with other plugins like the consolidation plugin. This plugin reports the same alarm as we get with the consolidation plugin. Is it possible to exclude that? Or the two plugins should be merged.

**Comment by atc0005** [comment]
@tubby1981 

> There is overlap with other plugins like the consolidation plugin.

I'm not too surprised by that, but agree that it could be a challenge. 

As you noted, depending on how vSphere records/reports the events, the same issue could be reported by multiple plugins. As another example, the datastore monitoring plugin (`check_vmware_datastore`) could report a disk space problem which may also be reported by the new `check_vmware_alarms` plugin) (or not, depending on whether the threshold values are the same).

> This plugin reports the same alarm as we get with the consolidation plugin. Is it possible to exclude that?

Currently, the `check_vmware_alarms` plugin offers the ability to filter (include or exclude) based on object type, so you could exclude all alarms for the `VirtualMachine` object type, but not (at present) just alarms related to disk consolidation.

> Or the two plugins should be merged.

I think it's worth keeping them separate. I could see how some sites would want to monitor for disk consolidation issues, but not want to monitor for unacknowledged alarms. It could be that a site has another team that monitors for issues at the datacenter level where they may only be interested in monitoring their VMs at their resource pool level.

While a lot of effort was put into the `check_vmware_alarms` plugin, I understand that it's current (initial release) state is fairly limited. I hope to extend it further with changes noted on #220 as time permits. If you could provide sanitized versions of what you're getting on your end that could prove helpful with further development efforts. 

In particular, fixed strings and/or screenshots from defined alarms within your environment would also be helpful. Those values could be retrieved by using the `Managed Object Browser` or `MOB` subURI.

For example:

  https://vc1.example.org/mob/

You could then navigate down to any triggered alarms within an affected datacenter and post details specific to the alarms.

In our case, you roughly follow this path:

1. https://vc1.example.org/mob/
1. Login
1. Click on `content`
1. Scroll down to `rootFolder`
1. Click on `group-d1 (Datacenters)`
1. Scroll down to `triggeredAlarmState`
1. Open one or more entries (e.g., different tabs)
1. Open the link for `alarm`
1. For the `alarm` tab, click on `info` value
11. Screenshot or copy/paste those details into a new issue

Example:

![image](https://user-images.githubusercontent.com/36716992/119988099-61606a00-bf8b-11eb-948b-68f9d7f24bff.png)

Having screenshots (or complete copy/paste blocks of details) would help with future work on the plugin.

**Comment by atc0005** [comment]
@tubby1981 See https://github.com/atc0005/check-vmware/releases/tag/v0.17.0 (but use binaries from `v0.17.1` instead) release for additional "bulk" filtering functionality. 

Targeted, "selective" filtering functionality isn't yet available (e.g., "exclude cpu usage alarms for node1, but show me cpu usage alarms for all other vms"). That's planned for GH-254 and may take some time to work out.

**Comment by tubby1981** [comment]
I will test it and let you know

**Comment by tubby1981** [comment]
exclude-desc filter is not working when i use: "-trust-cert false" before -exclude-desc

**Comment by atc0005** [comment]
> @tubby1981: exclude-desc filter is not working when i use: "-trust-cert false" before -exclude-desc

Can you post your command definition and service check config blocks? Feel free to replace sensitive details with equivalent placeholder values. It is important that you keep the syntax the same so that I can see how the settings are used.

Please also post as a new issue to make this easier to track.

Thanks.

**Comment by atc0005** [comment]
Just in case you were not aware of these files:

- https://github.com/atc0005/check-vmware/blob/master/contrib/nagios/etc/nagios-plugins/config/vmware-alarms.cfg
- https://github.com/atc0005/check-vmware/blob/master/contrib/nagios/etc/nagios3/conf/hosts/servers/vc1.example.com.cfg

In case the usage wasn't clear, this should help illustrate setting up the command definitions and the service checks.

If you experience further issues please file a new report. That will make regressions easier to track/resolve.

Thanks.

**Comment by tubby1981** [comment]
I had defined -trust-cert before -exclude-desc in my command, but it's not allowed when I look at the links above.

But check_vmware_alarms works great by the way !!

**Comment by atc0005** [comment]
> @tubby1981: I had defined -trust-cert before -exclude-desc in my command, but it's not allowed when I look at the links above.

The example files I linked to are intended as a useful reference or starting point, but you should be able to define your command definitions with the flags in a different order if you like. As an example, I just successfully used the `check_vmware_alarms` plugin with this argument set (substituted with placeholder values):

```console
$ ./check_vmware_alarms \
  --username vc1-read-only-service-account \
  --password "PLACEHOLDER" \
  --server vc1.example.com \
  --trust-cert \
  --exclude-desc "cpu"
```

I split the arguments over multiple lines here for readability.

> But check_vmware_alarms works great by the way !!

Thank you! Building this plugin was challenging, but overall a good experience and I hope a good addition to the collection.
