### ISSUE TITLE
unexpected visible log output in Icingaweb2

### ISSUE THREAD

**Issue by Byolock** [atc0005/check-vmware#314]
When a service reaches warning or critical state, the log output gets visible in icingaweb2 :

![grafik](https://user-images.githubusercontent.com/25748003/131318748-29825ce6-94b5-4737-81a4-6059c90bb874.png)

I wondered if it was expected and simply set the log level to fatal instead of info as a workaround, but based on this text it seems like it's not expected :

    Logging is enabled at the info level.

    this output is sent to stderr by default, which Nagios ignores
    this output is only seen (at least as of Nagios v3.x) when invoking the plugin directly via CLI (often for troubleshooting)
    
Unfortunately, I wasn't able to find information on how Icinga2 / Icingaweb2 differs from Nagios v3.x in this regard.
Do you recommend to just stay on log level fatal or do you want to develop a fix? I will provide any useful info I can in case you need some.

**Comment by atc0005** [comment]
Thanks for the report. Most of my experience has been with Nagios Core (v3 mostly, v4 recently) and only a small exposure to Nagios XI. While Icinga has been on my list to try, I've not used it.

Nagios doesn't use `stderr`, so at a very basic level I relied on that across all plugins in the project (and others based on the same logic) to use `stderr` as a way of emitting details useful for troubleshooting.

I don't believe that `fatal` is used at present (though the option is valid), so using that is probably a good choice for your environment (depending on how the web UI for Icinga displays the details). However if you don't want any output emitted at all, try passing `disabled` for the `log-level` flag.

Does this accomplish what you're looking to do?

**Comment by Byolock** [comment]
Yes that's fine I'll simply put the log level in the command template. Can be closed if you want.

**Comment by atc0005** [comment]
> @Byolock: Yes that's fine I'll simply put the log level in the command template. Can be closed if you want.

Thanks for the feedback, and for giving this project a try.

I'll close after a bit, but in the meantime will try to think of a way to convey setting `--log-level "disabled"` for `Icingaweb2` use.

**Comment by atc0005** [comment]
Spun off separate discussion item here for potential long-term changes:

- https://github.com/atc0005/check-vmware/discussions/323

**Comment by atc0005** [comment]
> > @Byolock: Yes that's fine I'll simply put the log level in the command template. Can be closed if you want.
> 
> Thanks for the feedback, and for giving this project a try.
> 
> I'll close after a bit, but in the meantime will try to think of a way to convey setting `--log-level "disabled"` for `Icingaweb2` use.

Updated README (GH-324) to provide additional coverage regarding the use of `stderr`. See also GH-323 for further discussion.

Thanks again for raising the issue.
