### ISSUE TITLE
Add initial support for Nagios Performance Data output

### ISSUE THREAD

**Issue by atc0005** [atc0005/check-vmware#321]
As discussed on GH-315, providing this support would be useful for Nagios (and Icinga) instances which support collecting/parsing Performance Data emitted by monitoring plugins.

I do not currently have Nagios or Icinga instances available for testing the changes, so will need to rely on others (e.g., as @Byolock has so kindly offered) for this testing & feedback.

I plan to update plugins in this project gradually as the final form of the initial Performance Data support added in atc0005/go-nagios#81 stabilizes.

**Comment by atc0005** [comment]
The initial build emits values with dashes separating the words. The official docs don't seem to indicate whether camel case, dashes, underscores or something else is preferred, so I'm digging further to see what the common pattern is for popular plugins.

Some examples of plugins (very brief search) which explicitly use underscores:

- https://github.com/mzupan/nagios-plugin-mongodb/blob/master/check_mongodb.py
- https://github.com/stdevel/nagios-plugins/blob/master/check_yum.py

**Comment by atc0005** [comment]
> The official docs don't seem to indicate whether camel case, dashes, underscores or something else is preferred

I evidently didn't real well enough, as the example on the https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/3/en/perfdata.html page illustrates using underscores:

> Plugins can return optional performance data in their output by sending the normal, human-readable text string that they usually would, followed by a pipe character (|), and then a string containing one or more performance data metrics. Let's take the check_ping plugin as an example and assume that it has been enhanced to return percent packet loss and average round trip time as performance data metrics. Sample output from the plugin might look like this:
> 
> `PING ok - Packet loss = 0%, RTA = 0.80 ms | percent_packet_loss=0, rta=0.80`
> 
> When Nagios sees this plugin output format it will split the output into two parts:
> 
> Everything before the pipe character is considered to be the "normal" plugin output and will be stored in either the $HOSTOUTPUT$ or $SERVICEOUTPUT$ macro
> 
> Everything after the pipe character is considered to be the plugin-specific performance data and will be stored in the $HOSTPERFDATA$ or $SERVICEPERFDATA$ macro
> 
> In the example above, the $HOSTOUTPUT$ or $SERVICEOUTPUT$ macro would contain "PING ok - Packet loss = 0%, RTA = 0.80 ms" (without quotes) and the $HOSTPERFDATA$ or $SERVICEPERFDATA$ macro would contain "percent_packet_loss=0, rta=0.80" (without quotes).

**Comment by atc0005** [comment]
Currently waiting on feedback from [`v0.20.0-alpha.3`](https://github.com/atc0005/check-vmware/releases/tag/v0.20.0-alpha.3) before proceeding further with this.

**Comment by Byolock** [comment]
Sorry for taking a bit longer than I said initially to give you feedback. Unfortunately I don't get any performance data output from the host memory check . Sample Output (from the console, so performance data should be visible if there is any) : 

----Debug Log----

```
{"level":"debug","version":"check-vmware v0.20.0-alpha.3-0-g20fcc94 (https://github.com/atc0005/check-vmware)","logging_level":"debug","plugin_type":"host-system-memory","connection_timeout":"10s","username":"xxxxxx","user_domain":"","trust_cert":true,"server":"192.168.5.53","port":443,"host_system_name":"RAS07","datacenter_name":"not provided","host_system_memory_critical_usage":95,"host_system_memory_warning_usage":90,"time":"2021-09-27T08:56:19Z","caller":"github.com/atc0005/check-vmware/cmd/check_vmware_host_memory/main.go:101","message":"Logging into vSphere environment"}
{"level":"debug","version":"check-vmware v0.20.0-alpha.3-0-g20fcc94 (https://github.com/atc0005/check-vmware)","logging_level":"debug","plugin_type":"host-system-memory","connection_timeout":"10s","username":"xxxxxxx","user_domain":"","trust_cert":true,"server":"192.168.5.53","port":443,"host_system_name":"RAS07","datacenter_name":"not provided","host_system_memory_critical_usage":95,"host_system_memory_warning_usage":90,"time":"2021-09-27T08:56:19Z","caller":"github.com/atc0005/check-vmware/cmd/check_vmware_host_memory/main.go:120","message":"Successfully logged into vSphere environment"}
{"level":"debug","version":"check-vmware v0.20.0-alpha.3-0-g20fcc94 (https://github.com/atc0005/check-vmware)","logging_level":"debug","plugin_type":"host-system-memory","connection_timeout":"10s","username":"xxxxxxxx","user_domain":"","trust_cert":true,"server":"192.168.5.53","port":443,"host_system_name":"RAS07","datacenter_name":"not provided","host_system_memory_critical_usage":95,"host_system_memory_warning_usage":90,"time":"2021-09-27T08:56:19Z","caller":"github.com/atc0005/check-vmware/cmd/check_vmware_host_memory/main.go:133","message":"Retrieving host by name"}
[vsphere] 2021/09/27 08:56:19 get.go:262: It took 49.303235ms to execute getObjectByName func (and retrieve HostSystem object).
[vsphere] 2021/09/27 08:56:19 hosts.go:205: It took 49.335273ms to execute GetHostSystemByName func.
{"level":"debug","version":"check-vmware v0.20.0-alpha.3-0-g20fcc94 (https://github.com/atc0005/check-vmware)","logging_level":"debug","plugin_type":"host-system-memory","connection_timeout":"10s","username":"xxxxx","user_domain":"","trust_cert":true,"server":"192.168.5.53","port":443,"host_system_name":"RAS07","datacenter_name":"not provided","host_system_memory_critical_usage":95,"host_system_memory_warning_usage":90,"time":"2021-09-27T08:56:19Z","caller":"github.com/atc0005/check-vmware/cmd/check_vmware_host_memory/main.go:156","message":"Successfully retrieved host by name"}
{"level":"debug","version":"check-vmware v0.20.0-alpha.3-0-g20fcc94 (https://github.com/atc0005/check-vmware)","logging_level":"debug","plugin_type":"host-system-memory","connection_timeout":"10s","username":"xxxxxx","user_domain":"","trust_cert":true,"server":"192.168.5.53","port":443,"host_system_name":"RAS07","datacenter_name":"not provided","host_system_memory_critical_usage":95,"host_system_memory_warning_usage":90,"time":"2021-09-27T08:56:19Z","caller":"github.com/atc0005/check-vmware/cmd/check_vmware_host_memory/main.go:158","message":"Generating host memory usage summary"}
{"level":"debug","version":"check-vmware v0.20.0-alpha.3-0-g20fcc94 (https://github.com/atc0005/check-vmware)","logging_level":"debug","plugin_type":"host-system-memory","connection_timeout":"10s","username":"xxxxxxx","user_domain":"","trust_cert":true,"server":"192.168.5.53","port":443,"host_system_name":"RAS07","datacenter_name":"not provided","host_system_memory_critical_usage":95,"host_system_memory_warning_usage":90,"host_system_name":"RAS07","host_system_memory_used_percentage":91.24106823137183,"host_system_memory_remaining_percentage":8.75893176862818,"host_system_memory_total":"511.9GB","host_system_memory_used":"467.1GB","host_system_memory_remaining":"44.8GB","host_system_critical_threshold":95,"host_system_warning_threshold":90,"time":"2021-09-27T08:56:19Z","caller":"github.com/atc0005/check-vmware/cmd/check_vmware_host_memory/main.go:174","message":"HostSystem memory usage summary"}
{"level":"debug","version":"check-vmware v0.20.0-alpha.3-0-g20fcc94 (https://github.com/atc0005/check-vmware)","logging_level":"debug","plugin_type":"host-system-memory","connection_timeout":"10s","username":"xxxxxxxx","user_domain":"","trust_cert":true,"server":"192.168.5.53","port":443,"host_system_name":"RAS07","datacenter_name":"not provided","host_system_memory_critical_usage":95,"host_system_memory_warning_usage":90,"time":"2021-09-27T08:56:19Z","caller":"github.com/atc0005/check-vmware/cmd/check_vmware_host_memory/main.go:176","message":"Retrieving VMs for host"}
[vsphere] 2021/09/27 08:56:20 get.go:118: It took 607.619226ms to execute getObjects func (and retrieve 95 VirtualMachine objects).
[vsphere] 2021/09/27 08:56:20 vms.go:471: It took 29.728µs to execute dedupeVMs func (evaluated 95 VMs).
[vsphere] 2021/09/27 08:56:20 vms.go:176: It took 607.799331ms to execute GetVMsFromContainers func (and retrieve 95 VMs).
{"level":"debug","version":"check-vmware v0.20.0-alpha.3-0-g20fcc94 (https://github.com/atc0005/check-vmware)","logging_level":"debug","plugin_type":"host-system-memory","connection_timeout":"10s","username":"xxxxxxxx","user_domain":"","trust_cert":true,"server":"192.168.5.53","port":443,"host_system_name":"RAS07","datacenter_name":"not provided","host_system_memory_critical_usage":95,"host_system_memory_warning_usage":90,"time":"2021-09-27T08:56:20Z","caller":"github.com/atc0005/check-vmware/cmd/check_vmware_host_memory/main.go:194","message":"Evaluating host memory usage state"}
{"level":"error","version":"check-vmware v0.20.0-alpha.3-0-g20fcc94 (https://github.com/atc0005/check-vmware)","logging_level":"debug","plugin_type":"host-system-memory","connection_timeout":"10s","username":"xxxxxxxx","user_domain":"","trust_cert":true,"server":"192.168.5.53","port":443,"host_system_name":"RAS07","datacenter_name":"not provided","host_system_memory_critical_usage":95,"host_system_memory_warning_usage":90,"host_name":"RAS07","host_usage_used_percentage":91.24106823137183,"host_usage_remaining_percentage":8.75893176862818,"host_memory_remaining":"44.8GB","time":"2021-09-27T08:56:20Z","caller":"github.com/atc0005/check-vmware/cmd/check_vmware_host_memory/main.go:230","message":"host memory usage threshold crossed"}
[vsphere] 2021/09/27 08:56:20 vms.go:395: It took 68.602µs to execute FilterVMsByPowerState func (for 95 VMs, yielding 65 VMs)
[vsphere] 2021/09/27 08:56:20 hosts.go:380: It took 115.849µs to execute HostSystemMemoryUsageOneLineCheckSummary func.
[vsphere] 2021/09/27 08:56:20 hosts.go:432: It took 255.885µs to execute HostSystemMemoryUsageReport func.


WARNING: Host RAS07 using 466.8GB (91.18%) of 511.9GB with 45.1GB (8.82%) remaining (65 visible VMs using 460.6GB (89.98%) memory)

**ERRORS**

* host memory usage exceeds specified threshold

**THRESHOLDS**

* CRITICAL: 95% memory usage
* WARNING: 90% memory usage

**DETAILED INFO**

Host Summary:

* Name: RAS07
* Memory
** Used by all VMs: 466.8GB (91.18%)
** Used by visible VMs: 460.6GB (89.98%)
** Remaining: 45.1GB (8.82%)
* VMs
** Visible: 95
** Running: 65
** Off: 30

VMs on host consuming memory (descending order):

* Qgis01 (Memory: 28.0GB, Host Memory Usage: 5.47%)
* SPSS25-03 (Memory: 16.1GB, Host Memory Usage: 3.15%)
* Qgis03 (Memory: 16.1GB, Host Memory Usage: 3.14%)

VMs on host not consuming memory:

* BUR-VM-2020
* CSR Englisch
* devwiki
* Endnote Test
* InDesign01

---

* vSphere environment: https://192.168.5.53:443/sdk
* Plugin User Agent: check-vmware/v0.20.0-alpha.3-0-g20fcc94 
```

The same for CPU Output. I haven't tested anything else yet cause I'm not sure on which checks I should expect performance data. Anything I may have missed? Version seems to be the right one if I look at the "Plugin User Agent" value from the output.

**Comment by atc0005** [comment]
> Unfortunately I don't get any performance data output from the host memory check . 

The only plugin emitting Performance Data at this point is the check_vmware_datastore plugin.

**Comment by Byolock** [comment]
Ok thanks I remember now that you talked about that specific plugin. 
Will test the datastore plugin in a moment and report back.

**Comment by atc0005** [comment]
> Ok thanks I remember now that you talked about that specific plugin.

I limited the changes to the `check_vmware_datastore` plugin for now as I don't have a great degree of confidence yet in the formatting of the PerfData output. Once we can confirm that everything looks good with the values emitted thus far I plan to expand that support.

> Will test the datastore plugin in a moment and report back.

Thanks.

**Comment by Byolock** [comment]
Okay so the good news first : 
I got performance data output, icinga2 recognizes it as performance data and Grafana creates a graph for them just fine.
The bad news : 
That is only true for _datastore_usage_ , the _datastore_storage_remaining_ values remain in the plugin output and are not recognized as performance data.

Datastore Plugin Check Output :
```
|'datastore_usage'=86.31%;90;95;;
'datastore_storage_remaining'=3640654823424B;;;0;26590947835904
```

For comparison the included ping check command output : 
`PING OK - Packet loss = 0%, RTA = 2.74 ms|rta=2.743000ms;3000.000000;5000.000000;0.000000 pl=0%;80;100;0`

The ping check plugin puts all performance data in one line and separates them with spaces. 
If you want to put them in seperate lines, from my understanding every line should start with a `|`.
Additionally as written here : https://nagios-plugins.org/doc/guidelines.html#AEN200 every line should end with a space.

**Comment by atc0005** [comment]
Thanks for testing and for the detailed feedback.

I was attempting to place the performance data at the end of the output as noted here:

https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/3/en/pluginapi.html

Specifically, "Case 3":

![case 3](https://user-images.githubusercontent.com/36716992/134918889-9f5369a0-ad07-4062-8d6b-0cb588408f08.png)

```
A plugin optionally return multiple lines of both text output and perfdata, like such:

DISK OK - free space: / 3326 MB (56%); | /=2643MB;5948;5958;0;5968
/ 15272 MB (77%);
/boot 68 MB (69%);
/home 69357 MB (27%);
/var/log 819 MB (84%); | /boot=68MB;88;93;0;98
/home=69357MB;253404;253409;0;253414
/var/log=818MB;970;975;0;980
```

I was attempting to only provide the output at the end instead of mixing it between the first line and latter lines.

I was on the fence regarding placing it at the end or only at the beginning just after the `ServiceOutput` (`$SERVICEOUPTUT$`). I was talking myself into the former based on the off-chance that `$LONGSERVICEOUTPUT$` runs long and results in truncated parsing related to [this limitation](https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/3/en/pluginapi.html), but hadn't decided yet:

> Plugin Output Length Restrictions
> 
> Nagios will only read the first 4 KB of data that a plugin returns. This is done in order to prevent runaway plugins from dumping megs or gigs of data back to Nagios. This 4 KB output limit is fairly easy to change if you need. Simply edit the value of the MAX_PLUGIN_OUTPUT_LENGTH definition in the include/nagios.h.in file of the source code distribution and recompile Nagios. There's nothing else you need to change!

> *the datastore_storage_remaining* values remain in the plugin output and are not recognized as performance data.

I'll take a closer look at this. Thanks for providing the exact output.

> If you want to put them in seperate lines, from my understanding every line should start with a `|`.

I couldn't find examples of that. I'll look again, but from what I recall the `|` signified the beginning of performance data relying on a 

> Additionally as written here : https://nagios-plugins.org/doc/guidelines.html#AEN200 every line should end with a space.

Apologies, I must be overlooking that. I see where it mentions space separating the label/value pairs, but the https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/3/en/pluginapi.html guide appears to indicate that newlines are equivalent whitespace to "space separated" as noted in https://nagios-plugins.org/doc/guidelines.html#AEN200.

I'm going to make a quick, minor change for the next alpha build to test whether the lack of the final trailing newline is to blame here.

**Comment by atc0005** [comment]
> I'm going to make a quick, minor change for the next alpha build to test whether the lack of the final trailing newline is to blame here.

@Byolock Done. Ready for testing.

**Comment by Byolock** [comment]
Nothing changed. 

> I couldn't find examples of that. I'll look again, but from what I recall the | signified the beginning of performance data relying on a

I read that part of the documentation again and I think you are right the single | at the beginning should be sufficient. 

>  I was attempting to place the performance data at the end of the output as noted here:
> 
> https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/3/en/pluginapi.html
> 
> Specifically, "Case 3":

I took a look at this and had to notice that in the 
`/home=69357MB;253404;253409;0;253414 `
line there is in fact a space at the end, but the other lines don't have one:

![grafik](https://user-images.githubusercontent.com/25748003/134933370-65777ec1-ebe8-4469-b564-c4ad4b8ae1f3.png)

In this part : 
![grafik](https://user-images.githubusercontent.com/25748003/134930408-5283839f-d42d-4807-b258-b421f38fd1fb.png)
Every label/value pair is separated by exactly one space, if every newline is equivalent to a space wouldn't be there two spaces in front of `/var/log=818MB;970;975;0;980` in the $SERVICEPERFDATA$ ?

Either they forgot the space after `/boot=68MB;88;93;0;98` or the double spaces in the $SERVICEPERFDATA$ value. Or I guess it could be that nagios has some sort of automatic removal for double spaces.

**Comment by atc0005** [comment]
> Every label/value pair is separated by exactly one space

I think that is the final form presented by Nagios to whatever tool (e.g., Grafana) is parsing performance data, but this is still somewhat new to me, so still figuring things out.

I'll have to do more digging and get back to you. Thanks for testing/feedback thus far.

**Comment by atc0005** [comment]
@Byolock 

I setup a test instance of Nagios 3 this AM on an Ubuntu 18.04 VM. I added a service check against a production VMware cluster's datastore and proceeded to test each alpha build of the `check_vmware_datastore` plugin, starting with alpha.4 down to alpha.2. 

Results for `v0.20.0-alpha.4-0-gee0509c`:

```
'datastore_usage'=44.53%;90;95;; 'datastore_storage_remaining'=1829583716352B;;;0;3298266447872
```

---

Results for `v0.20.0-alpha.3-0-g20fcc94`:

```
'datastore_usage'=44.53%;90;95;; 'datastore_storage_remaining'=1829583716352B;;;0;3298266447872
```

---

Results for `v0.20.0-alpha.2-0-g1eabb38`:

```
'datastore_usage'=44.53%;90;95;; 'datastore_storage_remaining'=1829583716352B;;;0;3298266447872
```

When I review the `ServiceOutput` content, it is the single line as expected.

When I review the `LongServiceOutput` content, it is everything that follows after the `ServiceOutput`, excluding Performance Data.

In my ignorance, this looks like the plugin is operating as intended?

**Comment by Byolock** [comment]
From what you've written I agree that sounds like the plugin is operating as intended on your end.

But this is what I get :

On console :
![grafik](https://user-images.githubusercontent.com/25748003/135089389-29e2ef48-10f2-4639-a4e3-266c4eb4e206.png)

This is what I see on the front end under Plugin Output:
![grafik](https://user-images.githubusercontent.com/25748003/135089573-7783c117-7b77-40bf-9eb9-ceb41187c0a2.png)

This is the list of performance Data on the front end :
![grafik](https://user-images.githubusercontent.com/25748003/135092230-1c53c751-81ca-41c3-9dd6-5cce9a78ec1b.png)
("Benachrichtigungen" means Notifications and is the heading for the next section on the frontend)

For comparison another check with multiple performance data metrics :
![grafik](https://user-images.githubusercontent.com/25748003/135092534-244ff93d-2f10-405c-a537-cbb8c3398287.png)


I'm running Ubuntu 20.04.

Could it be that Icinga2, again differs in this regard from Nagios 3? Their documentation can be found here : 
https://icinga.com/docs/icinga-2/latest/doc/05-service-monitoring/#performance-data-metrics but its pretty short, it doesn't mention multi line performance data syntax at all.

**Comment by atc0005** [comment]
Should have a new alpha build out in the AM. I'm modifying the output to place all metrics on one line, but still at the end of the output. 

While my intention of placing it at the very end of all output vs right after the `ServiceOutput` line was to make it easier to review the output while troubleshooting plugin execution (you wouldn't have the single-line output and perfdata "mixed" together on the same line), I'm thinking that it is probably going to end up being more compatible across Nagios-like platforms to stick to emitting right after `ServiceOutput` line.

This upcoming alpha doesn't use that approach, but I'm planning to release a follow-up using that approach.

**Comment by Byolock** [comment]
v0.20.0-alpha.5-0-g10a31bc works as intended on my end. 
Both values _datastore_storage_remaining_ and _datastore_usage_ are recognized as performance data values now. 
I'm sorry that I didn't found the Icinga2 Documentation that differs from the Monitoring Plugins project documentation earlier, would have saved us some time.

**Comment by atc0005** [comment]
> v0.20.0-alpha.5-0-g10a31bc works as intended on my end.
> Both values _datastore_storage_remaining_ and _datastore_usage_ are recognized as performance data values now.

That's great, thanks for testing that build.

> I'm sorry that I didn't found the Icinga2 Documentation that differs from the Monitoring Plugins project documentation earlier, would have saved us some time.

Not a problem, thanks for the detailed feedback you've been providing, it has been very helpful.

I had it in my mind that Nagios plugins were supported as-is by compatible monitoring platforms, so with that presumption in place I likely would have glossed over the details that we've been focusing on with the last few builds.

> While my intention of placing it at the very end of all output vs right after the `ServiceOutput` line was to make it easier to review the output while troubleshooting plugin execution (you wouldn't have the single-line output and perfdata "mixed" together on the same line), I'm thinking that it is probably going to end up being more compatible across Nagios-like platforms to stick to emitting right after `ServiceOutput` line.
> 
> This upcoming alpha doesn't use that approach, but I'm planning to release a follow-up using that approach.

This was going to be my next step, but I'm thinking now that maybe the changes for alpha.5 are sufficient. The data is getting picked up by Nagios and Incinga and the performance data is available to review by someone troubleshooting without mixing in with the single `ServiceOutput` line.

If we later learn that some values are not getting picked up we can tweak the output format further, moving it above the `LongServiceOutput`.

Now that the output format has been tested (thanks for your help with that), I'll focus on getting things sorted for an upcoming stable release.

**Comment by atc0005** [comment]
@Byolock working on a alpha.6 release to verify that everything still checks out after recent work. Getting ready to tag a stable release of the helper library that this project uses and wanted to do one last test before that.

Thanks.

**Comment by atc0005** [comment]
> @Byolock working on a alpha.6 release to verify that everything still checks out after recent work. Getting ready to tag a stable release of the helper library that this project uses and wanted to do one last test before that.
> 
> Thanks.

Follow-up: This release appears to work as intended with Nagios 3.x. Please test when you get a chance with Icinga.

Thanks for all of your help.

**Comment by Byolock** [comment]
I've tested alpha.6-0 with Icinga2 and it works as intended.

**Comment by atc0005** [comment]
> I've tested alpha.6-0 with Icinga2 and it works as intended.

Thank you, I appreciate you double-checking me on that.
