### ISSUE TITLE
Review `*_remaining` metrics, consider removing (or flipping) `Min` & `Max`

### ISSUE THREAD

**Issue by atc0005** [atc0005/check-vmware#480]
## Overview

As discussed in GH-315, `*_remaining` metrics flips the logic somewhat. Instead of a rising graph line indicating values of concern, it instead represents resources returning to a pool for later use (a "good thing"). By removing `Min` and `Max` values, this presumably results in a more easily understood (and useful?) value if used to generate trendlines. 

That said, (as originally indicated on GH-315) it may be worth flipping `Min` & `Max`. This might resolve any confusion around a larger number being a positive change and reflect the inverse of `*_used` metrics as originally intended.

## References

- GH-435 
- GH-315

**Comment by Byolock** [comment]
I agree that the `*_remaining` metrics need different `Min` and `Max` values than the `*_used` metrics. 
I personally don't use these values for graphs and use `warning` and `critical` values to show when a trendline goes 'bad'.
Flipping would be the best for easy understanding but removing should also work just fine. So in the end my recommendation would be, if it doesnt make much work flipping these values flip them, if it does for some reason simply remove them.

**Comment by atc0005** [comment]
Thinking out loud:

What if the `*_usage` perfdata metrics continue to specify Min/Max values, but both `*_used` and `*_remaining` metrics provided only the value, not Min/Max values?

**Comment by atc0005** [comment]
> Thinking out loud:
> 
> What if the `*_usage` perfdata metrics continue to specify Min/Max values, but both `*_used` and `*_remaining` metrics provided only the value, not Min/Max values?

I'm thinking that this is probably the way to go. Based on what I've seen elsewhere the percentage based "usage" levels can be used to determine if metrics indicate a problem, whereas the `*_used` and `*_remaining` metrics could be used to show changes over time. Potentially for troubleshooting, but also just as likely to get a sense of usage for future planning purposes.

If they prove to not have value we can always remove the `*_used` and `*_remaining` metrics from all plugins at a later time.
