### ISSUE TITLE
Total memory calculation error in the check_vmware_rps_memory 

### ISSUE THREAD

**Issue by aucompbiker** [atc0005/check-vmware#668]
Adam,

After deploying v0.30.0 today our Nagios began reported critical errors for excessive memory usage for the Libraries' and Military REACH resource pools. See the information provided by Nagios for each resource pool below. The calculations for total memory appear to be off or something. Is this a bug or do we need to fix something in our configs?

Libraries:

> CRITICAL: 561.7GB (156.0%) memory used of 360.0GB allowed, 12.19% of 4.5TB total capacity (evaluated 4 Resource Pools)

Military REACH

> CRITICAL: 73.3GB (183.2%) memory used of 40.0GB allowed, 1.59% of 4.5TB total capacity (evaluated 1 Resource Pools)

**Comment by atc0005** [comment]
> > @aucompbiker After deploying v0.30.0 today
> 
> What version did you use last?

Nevermind, I've already spotted the problem. This one is on me.

**Comment by atc0005** [comment]
@aucompbiker Should be able to release a new build tomorrow for this.

Thanks again for the report.
